apiVersion : apps/v1
kind: Deployment
metadata:
  name: app1nginxaks 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1nginxaks
  template:
    metadata:
      labels:
        app: app1nginxaks 
    spec:
      containers:
        - name: app1nginxaks 
          image: sampleacrcheck.azurecr.io/sampleacrcheck:4656
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: acrsecret   
