apiVersion : apps/v1
kind: Deployment
metadata:
  name: app1nginxaks 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1nginxaks
  template:
    metadata:
      labels:
        app: app1nginxaks 
    spec:
      containers:
        - name: app1nginxaks 
          image: acraksdevops01.azurecr.io/sample-repo:4587
          ports:
          - containerPort: 80
